project_id = "ingaaajdylbgpxqpsyjh"

[functions.check-user-permission]
verify_jwt = true

[functions.apply-membership]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.news-24]
verify_jwt = false