"use strict";
const C=document.getElementById("c"),ctx=C.getContext("2d");
ctx.imageSmoothingEnabled=false;
const W=960,H=540,CW=45,CH=90;
const IMG={};
for(const [k,s] of Object.entries(window.MIMIWORA_SPRITES)){const im=new Image();im.src=s;IMG[k]=im}
const TYPES=["mimi","goban","nomo","kuro"];
const HERO_X={mimi:150,goban:370,nomo:590,kuro:810};

function R(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function T(s,x,y,z=16,c="#fff",align="left"){ctx.fillStyle=c;ctx.font=z+"px monospace";ctx.textAlign=align;ctx.fillText(s,x,y);ctx.textAlign="left"}
function P(x,y,w,h,title=""){R(x,y,w,h,"#06101deb");R(x+4,y+4,w-8,h-8,"#172943ee");ctx.strokeStyle="#dfd19a";ctx.lineWidth=2;ctx.strokeRect(x+2,y+2,w-4,h-4);if(title)T(title,x+12,y+19,12,"#f2dfa0")}
function bar(x,y,w,h,v,max,c){R(x,y,w,h,"#151922");R(x+2,y+2,Math.max(0,(w-4)*Math.max(0,v)/Math.max(1,max)),h-4,c)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function rnd(a,b){return a+Math.random()*(b-a)}
function wrap(s,x,y,max,lh=20,size=14,c="#fff"){ctx.font=size+"px monospace";ctx.fillStyle=c;let line="",yy=y;for(const ch of s){let q=line+ch;if(ctx.measureText(q).width>max){ctx.fillText(line,x,yy);line=ch;yy+=lh}else line=q}if(line)ctx.fillText(line,x,yy)}
function drawSprite(k,tier,frame,x,base,scale=2.02,alpha=1){const im=IMG[k];if(!im||!im.complete)return;ctx.save();ctx.globalAlpha=alpha;let dw=CW*scale,dh=CH*scale;ctx.drawImage(im,frame*CW,tier*CH,CW,CH,x-dw/2,base-dh,dw,dh);ctx.restore()}
function flo(x,y,s,c="#fff"){game.floaters.push({x,y,s,c,t:.75})}
function vib(ms=20){if(navigator.vibrate)navigator.vibrate(ms)}

const HERO_BASE={
  mimi:{name:"MIMI",role:"星術師",hp:120,atk:21,rate:1.00,range:430,color:"#9fdfff"},
  goban:{name:"GOBAN",role:"守城拳士",hp:190,atk:31,rate:1.28,range:205,color:"#ffd765"},
  nomo:{name:"NOMO",role:"魔舌紳士",hp:138,atk:24,rate:1.02,range:330,color:"#a8e77f"},
  kuro:{name:"KURO",role:"影刃貓",hp:110,atk:18,rate:.54,range:245,color:"#ddddef"}
};

const WEAPONS={
mimi:[
 {name:"星錨法杖",tag:"均衡",unlock:1,desc:"星彈爆炸，適合清群",mods:{atk:1,rate:1,range:1,splash:18},skills:[
  ["星錨增幅","傷害 +35%",h=>h.atk*=1.35],["流星連發","攻速 +24%",h=>h.rate*=.76],["星爆擴散","爆炸半徑 +28",h=>h.splash+=28]]},
 {name:"月潮法典",tag:"控場",unlock:2,desc:"大型月潮魔法，命中減速",mods:{atk:.9,rate:1.18,range:1.08,splash:38,slow:.18},skills:[
  ["月潮擴張","範圍 +34",h=>h.splash+=34],["凍結潮汐","減速 +16%",h=>h.slow+=.16],["滿月爆發","傷害 +45%",h=>h.atk*=1.45]]},
 {name:"彗星弩",tag:"高速",unlock:3,desc:"高速單體輸出，暴擊更高",mods:{atk:.78,rate:.58,range:1.15,crit:.14},skills:[
  ["彗星核心","暴擊 +18%",h=>h.crit+=.18],["三連星","20% 追加兩發",h=>h.multishot+=.20],["超載弩弦","攻速 +27%",h=>h.rate*=.73]]}
],
goban:[
 {name:"鋼拳套",tag:"震波",unlock:1,desc:"近距震波，兼顧輸出與防線",mods:{atk:1,rate:1,range:1,shock:70},skills:[
  ["鋼拳增幅","傷害 +42%",h=>h.atk*=1.42],["震地衝擊","暈眩 +25%",h=>h.stun+=.25],["鐵壁反擊","城門減傷 +8%",h=>h.guard+=.08]]},
 {name:"雷槌",tag:"範圍",unlock:2,desc:"慢而重，巨大範圍與暈眩",mods:{atk:1.28,rate:1.35,range:1.08,shock:108,stun:.12},skills:[
  ["雷鳴重擊","傷害 +38%",h=>h.atk*=1.38],["雷域擴張","震波 +42",h=>h.shock+=42],["麻痺電流","暈眩 +20%",h=>h.stun+=.20]]},
 {name:"守城盾炮",tag:"防守",unlock:3,desc:"射程提升並強化城門護盾",mods:{atk:.86,rate:1.08,range:1.85,cannon:1,guard:.12},skills:[
  ["盾炮穿甲","傷害 +32%",h=>h.atk*=1.32],["堡壘協定","城門減傷 +12%",h=>h.guard+=.12],["爆裂彈","爆炸半徑 +32",h=>h.splash+=32]]}
],
nomo:[
 {name:"赤舌鞭",tag:"穿刺",unlock:1,desc:"直線舌擊，連續穿透",mods:{atk:1,rate:1,range:1,pierce:1},skills:[
  ["魔舌延伸","射程 +25%",h=>h.range*=1.25],["穿刺舌擊","穿透 +1",h=>h.pierce++],["狂舌強化","傷害 +36%",h=>h.atk*=1.36]]},
 {name:"酸液噴射器",tag:"持續傷",unlock:2,desc:"酸液腐蝕並持續減速",mods:{atk:.78,rate:.82,range:.86,acid:1,slow:.12},skills:[
  ["腐蝕濃度","酸傷 +55%",h=>h.dot*=1.55],["黏液覆蓋","減速 +18%",h=>h.slow+=.18],["高壓噴射","射程 +28%",h=>h.range*=1.28]]},
 {name:"電磁叉",tag:"連鎖",unlock:3,desc:"電弧跳躍多個敵人",mods:{atk:.9,rate:.95,range:1.15,chain:2},skills:[
  ["高壓電弧","連鎖 +1",h=>h.chain++],["感電增幅","傷害 +34%",h=>h.atk*=1.34],["超導核心","攻速 +23%",h=>h.rate*=.77]]}
],
kuro:[
 {name:"影刃",tag:"暴擊",unlock:1,desc:"高速斬擊，暴擊率高",mods:{atk:1,rate:1,range:1,crit:.10},skills:[
  ["疾風影刃","攻速 +25%",h=>h.rate*=.75],["月影暴擊","暴擊 +18%",h=>h.crit+=.18],["殘影追斬","追加斬擊 +20%",h=>h.clone+=.20]]},
 {name:"雙月匕首",tag:"極速",unlock:2,desc:"極快攻速，較低單擊傷害",mods:{atk:.70,rate:.46,range:.88,clone:.18},skills:[
  ["雙月連斬","追加斬擊 +22%",h=>h.clone+=.22],["無聲步","攻速 +20%",h=>h.rate*=.80],["背刺本能","暴擊 +16%",h=>h.crit+=.16]]},
 {name:"月輪",tag:"遠程",unlock:3,desc:"月輪飛返，適合中距離清怪",mods:{atk:.92,rate:.92,range:1.55,boomerang:1,pierce:1},skills:[
  ["月輪貫穿","穿透 +1",h=>h.pierce++],["回旋增幅","傷害 +35%",h=>h.atk*=1.35],["影輪雙生","25% 追加月輪",h=>h.multishot+=.25]]}
]};

const STAGES=[
 {id:1,name:"屍喪攻城",sub:"鐘聲停止後的第一夜",palette:["#17213a","#435a70","#5a4d43"],boss:"屍王・腐鐘",duration:95,unlockWeapon:2,
 intro:[["MIMI","夢城的鐘……真的停了。"],["KURO","城外不是霧，是屍群。數量比剛才多十倍。"],["GOBAN","……守住門。"],["NOMO","好！先把佢哋打到連自己個名都唔記得！"]],
 outro:[["MIMI","屍王身上有一塊發光碎片。"],["KURO","像是鐘芯的一部分。有人故意把它打碎。"],["NOMO","所以……這不是普通喪屍事件？"],["GOBAN","……下一站。黑雨街區。"]]},
 {id:2,name:"黑雨街區",sub:"毒雨下的失聯商業區",palette:["#10232c","#27414c","#28423d"],boss:"毒屠夫・M-9",duration:102,unlockWeapon:3,
 intro:[["NOMO","呢場雨有味……而且係好唔應該有嘅味。"],["MIMI","雨水裡有病毒反應。街區深處有人在擴散它。"],["KURO","那就把源頭揪出來。"],["GOBAN","……快。"]],
 outro:[["MIMI","第二塊鐘芯碎片。"],["KURO","上面有研究所標誌。"],["NOMO","咁我估下一關一定係地下實驗室啦。"],["GOBAN","……你今次估啱。"]]},
 {id:3,name:"地下研究所",sub:"病毒與鐘芯實驗的真相",palette:["#111a24","#293340","#3b3d48"],boss:"實驗體・OMEGA",duration:108,unlockWeapon:3,
 intro:[["MIMI","紀錄顯示：有人用鐘芯能量重寫感染者的記憶。"],["KURO","所以喪屍不是『死者』，而是被奪走自我的人。"],["NOMO","即係我哋唔只係守城，仲要救返佢哋。"],["GOBAN","……摧毀核心。"]],
 outro:[["MIMI","研究所主機提到一列運送鐘芯的月蝕列車。"],["KURO","如果列車把碎片送到中央塔，一切就太遲。"],["NOMO","追車？我鍾意。"],["GOBAN","……走。"]]},
 {id:4,name:"月蝕列車",sub:"高速移動的感染運輸線",palette:["#1e1326","#3a263f","#513746"],boss:"列車長・REAPER",duration:112,unlockWeapon:3,
 intro:[["KURO","列車時速很高，敵人會比之前更快。"],["MIMI","我感覺到第四塊碎片就在車頭。"],["NOMO","今次唔係守城，係守住我哋自己唔好跌落車。"],["GOBAN","……抓緊。"]],
 outro:[["MIMI","四塊碎片共鳴了。最後一塊……在夢城中央塔。"],["KURO","原來所有屍群只是把我們逼離城的誘餌。"],["NOMO","咁就返屋企，同幕後黑手埋單。"],["GOBAN","……最後一戰。"]]},
 {id:5,name:"夢城最後一夜",sub:"中央塔與末鐘核心",palette:["#241128","#52233e","#6b3944"],boss:"末鐘核心・NOX",duration:125,unlockWeapon:3,
 intro:[["MIMI","五塊鐘芯都在呼應……最後一塊就在塔內。"],["KURO","NOX 想讓所有人失去願望，這樣就不會有失望。"],["NOMO","聽落好似好有道理，但其實超級離譜。"],["GOBAN","……鐘要再響。"]],
 outro:[["NOX","願望只會帶來失敗。為甚麼還要保留？"],["MIMI","因為願望不是保證成功，而是提醒我們想往哪裡走。"],["KURO","失望不是刪除人生的理由。"],["NOMO","同埋……冇願望嘅世界，真係悶到爆。"],["GOBAN","……響鐘。"]]}
];

const ENEMIES={walker:{hp:38,spd:22,atk:10,xp:7,col:"#7c9065"},runner:{hp:29,spd:40,atk:8,xp:7,col:"#8ea16a"},tank:{hp:96,spd:13,atk:18,xp:15,col:"#66745a",armor:.14},spitter:{hp:48,spd:18,atk:13,xp:10,col:"#7c8760",ranged:1},acid:{hp:44,spd:20,atk:12,xp:10,col:"#6f9b63",acid:1},bomber:{hp:34,spd:29,atk:26,xp:12,col:"#9b6b57",bomb:1},shield:{hp:115,spd:15,atk:16,xp:17,col:"#6b7481",armor:.28},hunter:{hp:54,spd:48,atk:13,xp:13,col:"#755a83"},brute:{hp:175,spd:12,atk:20,xp:22,col:"#7b5537",armor:.10},boss1:{hp:720,spd:8.5,atk:31,xp:100,col:"#59624e"},boss2:{hp:820,spd:8.2,atk:34,xp:110,col:"#55714f"},boss3:{hp:900,spd:7.8,atk:36,xp:120,col:"#5b6574"},boss4:{hp:980,spd:9.2,atk:38,xp:130,col:"#654b69"},boss5:{hp:1250,spd:7.6,atk:42,xp:150,col:"#4e294b"}};

const SAVE_KEY="mimiwora_super_v1";function defaultSave(){return{unlockedStage:1,stars:{},weapons:{mimi:[0],goban:[0],nomo:[0],kuro:[0]},selected:{mimi:0,goban:0,nomo:0,kuro:0},seenPrologue:false,finished:false}}function loadSave(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY)||"null");return s?Object.assign(defaultSave(),s):defaultSave()}catch(e){return defaultSave()}}function store(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save))}catch(e){}}let save=loadSave();

let AC=null,master=null,musicTimer=null,musicStep=0,musicStage=1,muted=false;function audioInit(){if(AC)return;AC=new (window.AudioContext||window.webkitAudioContext)();master=AC.createGain();master.gain.value=.18;master.connect(AC.destination);startMusic()}function tone(f,d=.08,type="square",vol=.08,when=0){if(!AC||muted)return;const o=AC.createOscillator(),g=AC.createGain(),t=AC.currentTime+when;o.type=type;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(master);o.start(t);o.stop(t+d)}function noise(d=.06,vol=.04){if(!AC||muted)return;const b=AC.createBuffer(1,AC.sampleRate*d,AC.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const s=AC.createBufferSource(),g=AC.createGain();s.buffer=b;g.gain.value=vol;s.connect(g);g.connect(master);s.start();g.gain.exponentialRampToValueAtTime(.0001,AC.currentTime+d)}
function sfx(n){if(n==="mimi"){tone(740,.05,"triangle",.13);tone(980,.07,"sine",.07,.04)}if(n==="goban"){tone(105,.07,"square",.15);noise(.04,.05)}if(n==="nomo"){tone(210,.06,"square",.11);tone(150,.06,"square",.07,.05)}if(n==="kuro"){noise(.03,.05);tone(510,.04,"sawtooth",.07)}if(n==="kill"){tone(420,.04,"square",.06);tone(650,.05,"triangle",.04,.03)}if(n==="level"){[523,659,784].forEach((f,i)=>tone(f,.09,"square",.09,i*.08))}if(n==="boss"){tone(80,.38,"sawtooth",.12);tone(68,.38,"sawtooth",.09,.12)}if(n==="win"){[523,659,784,1046].forEach((f,i)=>tone(f,.16,"triangle",.11,i*.08))}if(n==="ultimate"){[523,659,784,1046,1318].forEach((f,i)=>tone(f,.18,"triangle",.10,i*.06))}if(n==="gate"){tone(65,.12,"sawtooth",.12);noise(.09,.06)}}
const THEMES=[{root:110,lead:[440,0,523,494,440,392,440,0,587,523,494,440,392,370,392,0]},{root:98,lead:[392,466,0,392,349,392,440,0,523,466,440,392,349,330,349,0]},{root:82,lead:[330,370,392,0,330,294,330,0,440,392,370,330,294,262,294,0]},{root:123.47,lead:[494,554,587,0,494,440,494,0,659,587,554,494,440,415,440,0]},{root:73.42,lead:[294,349,370,0,294,262,294,0,392,370,349,294,262,247,262,0]}];
function startMusic(){if(!AC||musicTimer)return;musicTimer=setInterval(()=>{if(muted)return;const th=THEMES[(musicStage-1)%THEMES.length],bass=th.root*(musicStep%8===4?1.5:1),lead=th.lead[musicStep%th.lead.length];tone(bass,.18,"square",.028);if(lead)tone(lead,.12,"triangle",.025,.02);if(musicStep%4===0)noise(.02,.012);musicStep++},210)}function setTheme(stage){musicStage=stage;musicStep=0}

const game={mode:"title",stageId:1,stage:null,story:[],storyI:0,storyAfter:null,selectedHero:"mimi",heroes:{},zombies:[],shots:[],fx:[],floaters:[],levelQueue:[],levelHero:null,skillCards:[],stageT:0,spawnT:.5,gateHP:360,gateMax:360,kills:0,bossSpawned:false,teamGauge:0,combo:0,comboT:0,shake:0,flash:"",flashT:0,resultStars:0,hoverStage:0};
function makeHero(k){const b=HERO_BASE[k],wi=save.selected[k]||0,w=WEAPONS[k][wi],m=w.mods;return{type:k,name:b.name,x:HERO_X[k],y:130,weapon:wi,weaponName:w.name,maxHp:b.hp,hp:b.hp,atk:b.atk*(m.atk||1),rate:b.rate*(m.rate||1),range:b.range*(m.range||1),level:1,xp:0,nextXp:28,cd:0,anim:"idle",animT:0,hit:0,splash:m.splash||0,slow:m.slow||0,crit:m.crit||.05,multishot:m.multishot||0,stun:m.stun||0,guard:m.guard||0,shock:m.shock||0,pierce:m.pierce||0,acid:m.acid||0,dot:m.acid?8:1,chain:m.chain||0,cannon:m.cannon||0,boomerang:m.boomerang||0,clone:m.clone||0,picked:[]}}
function resetBattle(stageId){game.stageId=stageId;game.stage=STAGES[stageId-1];game.heroes={};for(const k of TYPES)game.heroes[k]=makeHero(k);game.zombies=[];game.shots=[];game.fx=[];game.floaters=[];game.levelQueue=[];game.levelHero=null;game.skillCards=[];game.stageT=0;game.spawnT=.6;game.gateHP=360;game.gateMax=360;game.kills=0;game.bossSpawned=false;game.teamGauge=0;game.combo=0;game.comboT=0;game.shake=0;game.flash="";game.flashT=0;setTheme(stageId)}
function story(lines,after){game.story=lines.map(a=>({speaker:a[0],text:a[1]}));game.storyI=0;game.storyAfter=after;game.mode="story";syncControls()}function nextStory(){if(game.storyI<game.story.length-1){game.storyI++;tone(640,.03,"square",.03)}else{const fn=game.storyAfter;game.storyAfter=null;if(fn)fn()}}function speakerType(s){const map={MIMI:"mimi",GOBAN:"goban",NOMO:"nomo",KURO:"kuro"};return map[s]||null}function startStage(id){resetBattle(id);story(STAGES[id-1].intro,()=>{game.mode="battle";syncControls();game.flash="STAGE "+id+"  "+game.stage.name;game.flashT=2.0})}
function spawn(type,count=1){const d=ENEMIES[type];for(let i=0;i<count;i++)game.zombies.push({type,x:rnd(85,875),y:565+rnd(0,45),hp:d.hp*(1+(game.stageId-1)*.16),max:d.hp*(1+(game.stageId-1)*.16),atk:d.atk*(1+(game.stageId-1)*.08),spd:d.spd*(.92+rnd(0,.16)),xp:d.xp,col:d.col,armor:d.armor||0,hit:0,stun:0,slow:0,dot:0,dotT:0,cd:0,skillCd:5+rnd(0,3),anim:rnd(0,5)})}
function spawnLogic(dt){game.spawnT-=dt;if(game.spawnT<=0&&!game.bossSpawned){const t=game.stageT,s=game.stageId,r=Math.random();let type="walker";if(s===1){type=t>55&&r<.18?"tank":t>25&&r<.40?"runner":"walker"}if(s===2){type=t>60&&r<.18?"bomber":r<.45?"acid":r<.62?"runner":"walker"}if(s===3){type=t>62&&r<.20?"brute":r<.42?"shield":r<.62?"spitter":"walker"}if(s===4){type=t>70&&r<.18?"brute":r<.48?"hunter":r<.68?"runner":"shield"}if(s===5){type=r<.16?"brute":r<.32?"bomber":r<.48?"shield":r<.66?"hunter":"acid"}spawn(type);game.spawnT=Math.max(.22,1.15-game.stageT/180)*rnd(.72,1.20)}if(game.stageT>game.stage.duration&&!game.bossSpawned){game.bossSpawned=true;const bt="boss"+game.stageId;spawn(bt);sfx("boss");game.flash="BOSS  "+game.stage.boss;game.flashT=2.2;game.shake=8;spawn(game.stageId<3?"tank":"brute",4)}}
function targetFor(h){let best=null,bestD=1e9;for(const z of game.zombies){if(z.hp<=0)continue;let dy=z.y-h.y,dx=Math.abs(z.x-h.x),d=Math.hypot(dx*.8,dy);if(d<h.range&&d<bestD){best=z;bestD=d}}return best}
function damage(z,amount,source,color="#fff"){if(z.hp<=0)return;let dealt=amount*(1-(z.armor||0));z.hp-=dealt;z.hit=.08;game.teamGauge=clamp(game.teamGauge+dealt*.08,0,100);flo(z.x,z.y-75,"-"+Math.round(dealt),color);if(z.hp<=0){game.kills++;game.combo++;game.comboT=2.2;game.fx.push({kind:"death",x:z.x,y:z.y-35,t:.35});sfx("kill");if(source){gainXP(source,z.xp);for(const k of TYPES)if(game.heroes[k]!==source)gainXP(game.heroes[k],Math.max(1,Math.floor(z.xp*.28)))}}}
function gainXP(h,amt){if(h.level>=5)return;h.xp+=amt;while(h.level<5&&h.xp>=h.nextXp){h.xp-=h.nextXp;h.level++;h.nextXp=Math.round(h.nextXp*1.45+8);h.anim="celebrate";h.animT=1.0;game.levelQueue.push(h.type);sfx("level")}}
function attack(h,z){h.anim="attack";h.animT=.25;sfx(h.type);if(h.type==="mimi"){game.shots.push({kind:"star",x:h.x,y:h.y+15,target:z,spd:400,dmg:h.atk,source:h,splash:h.splash,slow:h.slow});if(Math.random()<h.multishot){game.shots.push({kind:"star",x:h.x+8,y:h.y+10,target:z,spd:430,dmg:h.atk*.65,source:h,splash:h.splash*.6,slow:h.slow});game.shots.push({kind:"star",x:h.x-8,y:h.y+18,target:z,spd:420,dmg:h.atk*.65,source:h,splash:h.splash*.6,slow:h.slow})}}else if(h.type==="goban"){if(h.cannon){game.shots.push({kind:"shell",x:h.x,y:h.y+20,target:z,spd:350,dmg:h.atk,source:h,splash:45+h.splash})}else{const rad=75+h.shock;game.fx.push({kind:"shock",x:h.x,y:h.y+55,t:.25,r:rad});for(const q of game.zombies){if(q.hp>0&&Math.hypot(q.x-h.x,q.y-(h.y+115))<rad){damage(q,h.atk*(q===z?1:.58),h,"#ffd66d");if(Math.random()<h.stun)q.stun=Math.max(q.stun,.8)}}}}else if(h.type==="nomo"){if(h.acid){game.fx.push({kind:"acid",x:h.x,y:h.y+15,ex:z.x,ey:z.y-25,t:.18});const targets=game.zombies.filter(q=>q.hp>0&&Math.abs(q.x-z.x)<70&&q.y>=z.y-40).slice(0,4);for(const q of targets){damage(q,h.atk*.72,h,"#b8f181");q.dot=Math.max(q.dot,h.dot);q.dotT=3;q.slow=Math.max(q.slow,h.slow)}}else if(h.chain){let pool=game.zombies.filter(q=>q.hp>0).sort((a,b)=>Math.hypot(a.x-z.x,a.y-z.y)-Math.hypot(b.x-z.x,b.y-z.y));let cur=z;for(let i=0;i<Math.min(h.chain+1,pool.length);i++){const q=pool[i];damage(q,h.atk*(1-i*.16),h,"#9eeeff");game.fx.push({kind:"arc",x:i?cur.x:h.x,y:i?cur.y:h.y+18,ex:q.x,ey:q.y-35,t:.12});cur=q}}else{game.fx.push({kind:"tongue",x:h.x,y:h.y+14,ex:z.x,ey:z.y-30,t:.16});const targets=game.zombies.filter(q=>q.hp>0&&Math.abs(q.x-z.x)<42&&q.y>=z.y-25).sort((a,b)=>a.y-b.y).slice(0,1+h.pierce);for(const q of targets)damage(q,h.atk,h,"#b9ed83")}}else{if(h.boomerang){game.shots.push({kind:"ring",x:h.x,y:h.y+15,target:z,spd:430,dmg:h.atk,source:h,pierce:h.pierce,returning:false});if(Math.random()<h.multishot)game.shots.push({kind:"ring",x:h.x+8,y:h.y+8,target:z,spd:450,dmg:h.atk*.75,source:h,pierce:h.pierce,returning:false})}else{let crit=Math.random()<h.crit,d=h.atk*(crit?2:1);damage(z,d,h,crit?"#fff19b":"#e7e7ff");game.fx.push({kind:"slash",x:z.x,y:z.y-35,t:.16});if(Math.random()<h.clone){damage(z,h.atk*.7,h,"#c5c8ff");flo(z.x,z.y-90,"殘影","#cbd2ff")}}}}
function updateShots(dt){for(const s of game.shots){if(s.kind==="ring"&&s.returning){let dx=s.source.x-s.x,dy=(s.source.y+15)-s.y,d=Math.hypot(dx,dy);if(d<14){s.dead=true;continue}s.x+=dx/d*s.spd*dt;s.y+=dy/d*s.spd*dt;continue}if(!s.target||s.target.hp<=0){if(s.kind==="ring"){s.returning=true;continue}s.dead=true;continue}let tx=s.target.x,ty=s.target.y-38,dx=tx-s.x,dy=ty-s.y,d=Math.hypot(dx,dy);if(d<15){damage(s.target,s.dmg,s.source,s.kind==="shell"?"#ffd58a":"#b7eeff");if(s.splash){for(const q of game.zombies)if(q!==s.target&&q.hp>0&&Math.hypot(q.x-s.target.x,q.y-s.target.y)<s.splash)damage(q,s.dmg*.45,s.source,"#9fdcff")}if(s.slow)s.target.slow=Math.max(s.target.slow,s.slow);game.fx.push({kind:"spark",x:s.target.x,y:s.target.y-40,t:.2});if(s.kind==="ring"){s.pierce--;if(s.pierce>=0){let next=game.zombies.find(q=>q.hp>0&&q!==s.target&&Math.hypot(q.x-s.target.x,q.y-s.target.y)<120);if(next){s.target=next;continue}}s.returning=true;continue}s.dead=true}else{s.x+=dx/d*s.spd*dt;s.y+=dy/d*s.spd*dt}}game.shots=game.shots.filter(s=>!s.dead)}
function updateZombies(dt){let guard=0;for(const h of Object.values(game.heroes))guard=Math.max(guard,h.guard||0);for(const z of game.zombies){z.anim+=dt;z.hit=Math.max(0,z.hit-dt);z.stun=Math.max(0,z.stun-dt);z.cd-=dt;z.skillCd-=dt;if(z.dotT>0){z.dotT-=dt;if(z.dotT>0&&Math.floor(z.dotT*5)!==Math.floor((z.dotT+dt)*5))damage(z,z.dot*.2,null,"#a8ef79")}if(z.hp<=0||z.stun>0)continue;const boss=z.type.startsWith("boss");if(boss&&z.skillCd<=0){spawn(game.stageId<3?"runner":game.stageId<5?"hunter":"bomber",2+Math.floor(game.stageId/2));z.skillCd=6.5;game.shake=5;flo(z.x,z.y-115,"召喚","#ffb5ca")}if(z.y<=178){if(z.cd<=0){let dmg=z.atk*(1-guard);if(z.bomb)dmg*=1.5;game.gateHP-=dmg;flo(z.x,153,"-"+Math.round(dmg),"#ffb5bf");z.cd=1.0;sfx("gate");game.shake=Math.max(game.shake,4);if(z.bomb)z.hp=0}}else{let zig=(z.type==="hunter"?Math.sin(z.anim*7)*15*dt:0);z.x=clamp(z.x+zig,60,900);z.y-=z.spd*(1-clamp(z.slow,0,.65))*dt}}game.zombies=game.zombies.filter(z=>z.hp>0)}
function openLevel(){const k=game.levelQueue.shift();if(!k)return;game.levelHero=game.heroes[k];const w=WEAPONS[k][game.levelHero.weapon];game.skillCards=w.skills;game.mode="upgrade";syncControls()}function chooseSkill(i){if(!game.levelHero)return;const s=game.skillCards[i];if(!s)return;s[2](game.levelHero);game.levelHero.picked.push(s[0]);game.flash=game.levelHero.name+" Lv."+game.levelHero.level+"  "+s[0];game.flashT=1.5;game.levelHero=null;game.skillCards=[];if(game.levelQueue.length)openLevel();else{game.mode="battle";syncControls()}}function ultimate(){if(game.mode!=="battle"||game.teamGauge<100)return;game.teamGauge=0;sfx("ultimate");game.fx.push({kind:"ultimate",t:1.2});for(const z of game.zombies)damage(z,z.type.startsWith("boss")?95:62,null,"#c5f3ff");game.shake=8;vib(80)}
function endBattle(win){if(!win){game.mode="lose";syncControls();return}const hp=game.gateHP/game.gateMax;game.resultStars=hp>.72?3:hp>.38?2:1;const old=save.stars[game.stageId]||0;save.stars[game.stageId]=Math.max(old,game.resultStars);if(game.stageId<5)save.unlockedStage=Math.max(save.unlockedStage,game.stageId+1);else save.finished=true;if(game.stage.unlockWeapon===2||game.stage.unlockWeapon===3){for(const k of TYPES){for(let wi=0;wi<WEAPONS[k].length;wi++)if(WEAPONS[k][wi].unlock<=game.stage.unlockWeapon&&!save.weapons[k].includes(wi))save.weapons[k].push(wi)}}store();sfx("win");game.mode="result";syncControls()}
function updateBattle(dt){game.stageT+=dt;game.flashT=Math.max(0,game.flashT-dt);game.comboT-=dt;if(game.comboT<=0)game.combo=0;game.shake=Math.max(0,game.shake-dt*15);spawnLogic(dt);for(const h of Object.values(game.heroes)){h.cd-=dt;h.hit=Math.max(0,h.hit-dt);h.animT-=dt;if(h.animT<=0)h.anim="idle";const z=targetFor(h);if(z&&h.cd<=0){attack(h,z);h.cd=h.rate}}updateShots(dt);updateZombies(dt);game.fx.forEach(e=>e.t-=dt);game.fx=game.fx.filter(e=>e.t>0);game.floaters.forEach(f=>{f.t-=dt;f.y-=28*dt});game.floaters=game.floaters.filter(f=>f.t>0);if(game.levelQueue.length&&game.mode==="battle")openLevel();if(game.gateHP<=0){game.gateHP=0;endBattle(false)}if(game.bossSpawned&&!game.zombies.some(z=>z.type==="boss"+game.stageId)&&game.mode==="battle")endBattle(true)}
function heroTier(h){return h.level>=5?2:h.level>=3?1:0}function heroFrame(h){if(h.anim==="hurt")return 6;if(h.anim==="celebrate")return 7;if(h.anim==="attack")return Math.floor(performance.now()/90)%2?4:5;return Math.floor(performance.now()/800)%8===0?1:0}
function bg(pal,stage=0){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,pal[0]);g.addColorStop(.55,pal[1]);g.addColorStop(1,pal[2]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<46;i++)R((i*137+stage*23)%W,(i*83)%250,2,2,i%5?"#a8bdd1":"#eadba9");for(let i=0;i<10;i++){let x=i*105;R(x,250+(i%3)*12,92,120,i%2?"#1d2732":"#25313d");R(x+18,225+(i%2)*18,10,38,"#1b242e")}}function wall(){R(18,95,924,82,"#485364");R(28,105,904,62,"#6c7a8d");for(let x=34;x<930;x+=58)R(x,90,42,21,"#59687b");R(52,156,856,18,"#303946")}
function drawHeroes(){for(const h of Object.values(game.heroes)){const a=h.hit>0&&Math.floor(performance.now()/45)%2?.4:1;drawSprite(h.type,heroTier(h),heroFrame(h),h.x,190,2.02,a);T(h.name+" Lv."+h.level,h.x,64,11,HERO_BASE[h.type].color,"center");if(h.level<5)bar(h.x-38,72,76,5,h.xp,h.nextXp,"#ffd75d");else T("MAX",h.x,77,9,"#ffe77c","center");T(h.weaponName,h.x,88,9,"#dceeff","center")}}
function drawZombie(z){const s=z.type.startsWith("boss")?1.45:z.type==="brute"||z.type==="shield"?1.15:1,x=z.x,y=z.y,hit=z.hit>0;ctx.save();ctx.translate(x,y);if(z.type==="hunter")ctx.rotate(Math.sin(z.anim*7)*.04);R(-12*s,-45*s,24*s,26*s,hit?"#fff":z.col);R(-9*s,-38*s,6*s,6*s,"#d9e5b9");R(3*s,-38*s,6*s,6*s,"#d9e5b9");R(-6*s,-36*s,2*s,2*s,"#a62933");R(5*s,-36*s,2*s,2*s,"#a62933");if(z.type.startsWith("boss")){R(-15*s,-55*s,30*s,8*s,"#463a28");R(-10*s,-64*s,6*s,10*s,"#d5aa3e");R(3*s,-64*s,6*s,10*s,"#d5aa3e")}R(-10*s,-19*s,20*s,27*s,z.type==="shield"?"#3f4a58":"#4a594b");if(z.type==="shield")R(-18*s,-20*s,9*s,32*s,"#77818f");if(z.type==="bomber")R(10*s,-18*s,8*s,18*s,"#bc5d3f");R(-15*s,-14*s,5*s,19*s,"#6d805c");R(10*s,-14*s,5*s,19*s,"#6d805c");R(-8*s,8*s,6*s,14*s,"#343e39");R(2*s,8*s,6*s,14*s,"#343e39");ctx.restore();bar(x-24*s,y-75*s,48*s,5,z.hp,z.max,z.type.startsWith("boss")?"#e25977":"#d16b71")}
function drawFX(){for(const e of game.fx){const a=clamp(e.t/.3,0,1);ctx.globalAlpha=clamp(a,0,1);if(["spark","death"].includes(e.kind)){ctx.strokeStyle=e.kind==="spark"?"#c3f4ff":"#e3c39a";ctx.beginPath();ctx.arc(e.x,e.y,30*(1-a)+4,0,Math.PI*2);ctx.stroke()}if(e.kind==="slash"){ctx.strokeStyle="#eff2ff";ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,25,-2.5,-.2);ctx.stroke()}if(e.kind==="tongue"||e.kind==="acid"){ctx.strokeStyle=e.kind==="acid"?"#92e36c":"#e64f5c";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.ex,e.ey);ctx.stroke()}if(e.kind==="arc"){ctx.strokeStyle="#9eefff";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo((e.x+e.ex)/2+rnd(-8,8),(e.y+e.ey)/2+rnd(-8,8));ctx.lineTo(e.ex,e.ey);ctx.stroke()}if(e.kind==="shock"){ctx.strokeStyle="#ffd76e";ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,e.r*(1-a)+20,0,Math.PI);ctx.stroke()}if(e.kind==="ultimate"){ctx.strokeStyle="#bdf0ff";ctx.lineWidth=3;ctx.strokeRect(4,4,W-8,H-8);for(let i=0;i<22;i++)R((i*61+performance.now()/4)%W,190+(i%7)*45,4,28,"#c5f1ff")}ctx.globalAlpha=1}for(const f of game.floaters){ctx.globalAlpha=clamp(f.t/.75,0,1);T(f.s,f.x,f.y,12,f.c,"center");ctx.globalAlpha=1}}
function drawShots(){for(const s of game.shots){if(s.kind==="ring"){ctx.strokeStyle="#e9e9ff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(s.x,s.y,7,0,Math.PI*2);ctx.stroke()}else{R(s.x-4,s.y-4,8,8,s.kind==="shell"?"#ffd26f":"#baf0ff");R(s.x-1,s.y-8,2,16,"#fff")}}}
function hud(){P(12,12,210,64,"城門");T("HP",26,40,12,"#ffe6aa");bar(52,31,148,12,game.gateHP,game.gateMax,"#6ed5ff");T(Math.round(game.gateHP)+" / "+game.gateMax,126,58,10,"#fff","center");P(232,12,225,64,"關卡");T("CH."+game.stageId+" "+game.stage.name,248,40,14,"#fff");T("擊殺 "+game.kills+"　Combo x"+game.combo,248,58,10,"#cfe7ff");P(467,12,215,64,"四人合技");T(Math.round(game.teamGauge)+" / 100",483,39,12,game.teamGauge>=100?"#ffe77c":"#fff");bar(483,49,178,9,game.teamGauge,100,game.teamGauge>=100?"#ffe16d":"#75bde8");P(692,12,256,64,"目標");T(game.bossSpawned?game.stage.boss:"撐過 "+Math.max(0,Math.ceil(game.stage.duration-game.stageT))+" 秒",708,39,12,game.bossSpawned?"#ffbdcb":"#fff");T(game.teamGauge>=100?"Q：夢光流星 READY":"每位角色本關可升至 Lv.5",708,58,10,game.teamGauge>=100?"#ffe77c":"#cfe7ff")}
function renderBattle(){const pal=game.stage.palette;ctx.save();if(game.shake>0)ctx.translate(rnd(-game.shake,game.shake),rnd(-game.shake,game.shake));bg(pal,game.stageId);R(42,170,876,370,"#534943");R(60,186,840,354,"#62564b");wall();drawHeroes();for(const z of game.zombies)drawZombie(z);drawShots();drawFX();ctx.restore();hud();if(game.flashT>0){ctx.globalAlpha=Math.min(1,game.flashT);T(game.flash,480,220,22,"#ffe88a","center");ctx.globalAlpha=1}}
function renderTitle(){bg(["#08101e","#162a3e","#27394a"],0);T("MIMIWORA",480,84,52,"#efe0aa","center");T("末 鐘 守 城",480,126,30,"#a7e1ff","center");drawSprite("mimi",2,7,205,355,2.55);drawSprite("goban",2,7,390,355,2.55);drawSprite("nomo",2,7,575,355,2.55);drawSprite("kuro",2,7,760,355,2.55);P(170,368,620,108);T("五章故事・12 種武器・角色 Lv.5 Build・Boss 戰",480,401,17,"#ffe98c","center");T(save.finished?"世界已通關 — 仍可重玩刷三星":"鐘聲停止，夢城正在失去所有人的願望。",480,430,14,"#fff","center");T(save.seenPrologue?"按 ENTER 繼續":"按 ENTER 開始故事",480,458,18,"#aee7ff","center")}
function renderMap(){bg(["#10192d","#25364a","#4b5963"],0);T("夢城戰線",480,58,31,"#efe0aa","center");T("選擇關卡",480,84,14,"#cfe7ff","center");STAGES.forEach((s,i)=>{const unlocked=s.id<=save.unlockedStage,x=70+(i%3)*285,y=120+Math.floor(i/3)*170,w=250,h=135;R(x,y,w,h,unlocked?"#18304c":"#161b24");ctx.strokeStyle=unlocked?"#dfd09a":"#555";ctx.lineWidth=2;ctx.strokeRect(x+2,y+2,w-4,h-4);T("CH."+s.id,x+16,y+26,13,unlocked?"#ffe68a":"#777");T(s.name,x+16,y+52,18,unlocked?"#fff":"#777");wrap(s.sub,x+16,y+78,215,18,12,unlocked?"#cfe7ff":"#666");let st=save.stars[s.id]||0;T(unlocked?("★".repeat(st)+"☆".repeat(3-st)):"LOCK",x+16,y+116,16,unlocked?"#ffd75d":"#777");if(unlocked)T("點擊進入",x+225,y+116,10,"#aee8ff","right")});T("武器會隨故事進度解鎖；每關角色等級重新由 Lv.1 開始。",480,493,12,"#cfe7ff","center")}
function renderLoadout(){bg(["#10192d","#26394c","#3d4d5c"],0);T("出戰整備",480,48,29,"#efe0aa","center");T("CH."+game.stageId+"  "+STAGES[game.stageId-1].name,480,76,14,"#cfe7ff","center");TYPES.forEach((k,i)=>{const x=80+i*215,y=104,sel=game.selectedHero===k;R(x,y,180,110,sel?"#244d70":"#162b43");ctx.strokeStyle=sel?"#aeeaff":"#d9cc98";ctx.strokeRect(x+2,y+2,176,106);drawSprite(k,0,0,x+48,y+100,1.12);T(HERO_BASE[k].name,x+92,y+28,13,HERO_BASE[k].color);T(WEAPONS[k][save.selected[k]].name,x+92,y+52,11,"#fff");T(HERO_BASE[k].role,x+92,y+74,10,"#cfe7ff")});const k=game.selectedHero;T(HERO_BASE[k].name+" 武器",90,252,18,HERO_BASE[k].color);WEAPONS[k].forEach((w,i)=>{const x=90+i*270,y=275,owned=save.weapons[k].includes(i),sel=save.selected[k]===i;R(x,y,235,140,sel?"#284f70":owned?"#172e47":"#151922");ctx.strokeStyle=sel?"#b7eaff":owned?"#d9ca95":"#555";ctx.strokeRect(x+2,y+2,231,136);T((i+1)+". "+w.name,x+16,y+28,15,owned?"#ffe78a":"#777");T(w.tag,x+16,y+53,12,owned?"#aee8ff":"#777");wrap(w.desc,x+16,y+80,200,20,12,owned?"#fff":"#666");T(owned?(sel?"裝備中":"點擊裝備"):"完成前置關卡解鎖",x+16,y+124,10,owned?(sel?"#bdf1c7":"#cfe7ff"):"#777")});P(685,437,200,60);T("開始關卡",785,474,19,"#ffe88a","center");T("點角色可換武器",180,478,11,"#cfe7ff","center")}
function renderStory(){const s=game.story[game.storyI],kt=speakerType(s.speaker);bg(["#0d1423","#26384b","#3f4a55"],0);if(kt)drawSprite(kt,Math.min(2,Math.floor(game.stageId/2)),0,250,390,3.1);else{drawSprite("mimi",2,0,250,390,2.4);drawSprite("kuro",2,0,365,390,2.2)}P(410,170,475,230);T(s.speaker,445,208,20,kt?HERO_BASE[kt].color:"#ffb5ce");wrap(s.text,445,250,400,30,19,"#fff");T("ENTER / 點擊繼續",650,375,11,"#cfe7ff","center")}
function renderUpgrade(){renderBattle();R(0,0,W,H,"rgba(2,6,12,.75)");P(90,92,780,350,"LEVEL UP");T(game.levelHero.name+" 升到 Lv."+game.levelHero.level,480,134,25,HERO_BASE[game.levelHero.type].color,"center");T(game.levelHero.weaponName+" — 選擇強化方向",480,161,13,"#fff","center");game.skillCards.forEach((s,i)=>{let x=130+i*240,y=195;R(x,y,215,185,i===0?"#1b3855":"#172e47");ctx.strokeStyle="#dfd09a";ctx.strokeRect(x+2,y+2,211,181);T((i+1)+"",x+18,y+28,17,"#ffe77d");T(s[0],x+107,y+78,17,"#fff","center");wrap(s[1],x+24,y+118,165,24,15,"#cfe7ff")})}
function renderResult(){renderBattle();R(0,0,W,H,"rgba(0,0,0,.68)");P(170,125,620,290);T("CH."+game.stageId+" CLEAR",480,180,30,"#ffe88a","center");T("★".repeat(game.resultStars)+"☆".repeat(3-game.resultStars),480,226,34,"#ffd75d","center");T("擊殺 "+game.kills+"　城門剩餘 "+Math.round(game.gateHP/game.gateMax*100)+"%",480,264,14,"#fff","center");if(game.stageId<5)T("新故事與武器已解鎖",480,305,16,"#aee8ff","center");else T("末鐘核心已被擊破",480,305,16,"#aee8ff","center");T("按 ENTER 繼續",480,370,17,"#ffe88a","center")}
function renderLose(){renderBattle();R(0,0,W,H,"rgba(0,0,0,.68)");P(175,150,610,220);T("夢城失守",480,210,32,"#ffb4bf","center");wrap("這關不是只堆傷害就會贏。試下更換武器，或者在升級時加入控場、穿透、攻速或城門減傷。",250,255,460,26,16,"#fff");T("ENTER 重試｜點擊返回整備",480,335,14,"#ffe88a","center")}
function renderEnding(){bg(["#120d20","#3d2642","#644554"],5);T("鐘聲重新響起。",480,125,34,"#efe0aa","center");drawSprite("mimi",2,7,220,370,2.5);drawSprite("goban",2,7,395,370,2.5);drawSprite("nomo",2,7,570,370,2.5);drawSprite("kuro",2,7,745,370,2.5);wrap("夢城的人重新記起自己的願望。四個伙伴知道，這不是故事的終點，而是 MIMIWORA 真正冒險的開始。",220,420,520,28,17,"#fff");T("ENTER 返回戰線地圖",480,500,14,"#aee8ff","center")}
function render(){ctx.clearRect(0,0,W,H);if(game.mode==="title")renderTitle();else if(game.mode==="map")renderMap();else if(game.mode==="loadout")renderLoadout();else if(game.mode==="story")renderStory();else if(game.mode==="battle")renderBattle();else if(game.mode==="upgrade")renderUpgrade();else if(game.mode==="result")renderResult();else if(game.mode==="lose")renderLose();else if(game.mode==="ending")renderEnding()}
function syncControls(){const sp=document.getElementById("skillPad");sp.style.display=game.mode==="upgrade"?"flex":"none"}function toMap(){game.mode="map";syncControls()}
function handleKey(code){audioInit();if(code==="KeyM"){muted=!muted;if(master)master.gain.value=muted?0:.18;return}if(game.mode==="title"&&code==="Enter"){if(!save.seenPrologue){save.seenPrologue=true;store();story([["MIMI","今晚的鐘沒有響。"],["KURO","不是壞掉，是有人把『鐘芯』拆走了。"],["NOMO","然後全城開始出現喪屍。好，非常不妙。"],["GOBAN","……守城。找碎片。讓鐘再響。"]],toMap)}else toMap();return}if(game.mode==="story"&&(code==="Enter"||code==="Space")){nextStory();return}if(game.mode==="upgrade"){if(code==="Digit1")chooseSkill(0);if(code==="Digit2")chooseSkill(1);if(code==="Digit3")chooseSkill(2);return}if(game.mode==="battle"&&code==="KeyQ"){ultimate();return}if(game.mode==="result"&&code==="Enter"){const sid=game.stageId;story(STAGES[sid-1].outro,()=>{if(sid===5){game.mode="ending";syncControls()}else toMap()});return}if(game.mode==="lose"&&code==="Enter"){startStage(game.stageId);return}if(game.mode==="ending"&&code==="Enter"){toMap();return}}
addEventListener("keydown",e=>handleKey(e.code));function canvasXY(ev){const r=C.getBoundingClientRect();return{x:(ev.clientX-r.left)*W/r.width,y:(ev.clientY-r.top)*H/r.height}}C.addEventListener("pointerdown",ev=>{audioInit();const {x,y}=canvasXY(ev);if(game.mode==="title"){handleKey("Enter");return}if(game.mode==="story"){nextStory();return}if(game.mode==="map"){STAGES.forEach((s,i)=>{const xx=70+(i%3)*285,yy=120+Math.floor(i/3)*170;if(x>=xx&&x<=xx+250&&y>=yy&&y<=yy+135&&s.id<=save.unlockedStage){game.stageId=s.id;game.selectedHero="mimi";game.mode="loadout";syncControls()}});return}if(game.mode==="loadout"){TYPES.forEach((k,i)=>{const xx=80+i*215;if(x>=xx&&x<=xx+180&&y>=104&&y<=214)game.selectedHero=k});const k=game.selectedHero;WEAPONS[k].forEach((w,i)=>{const xx=90+i*270;if(x>=xx&&x<=xx+235&&y>=275&&y<=415&&save.weapons[k].includes(i)){save.selected[k]=i;store()}});if(x>=685&&x<=885&&y>=437&&y<=497)startStage(game.stageId);return}if(game.mode==="upgrade"){for(let i=0;i<3;i++){const xx=130+i*240;if(x>=xx&&x<=xx+215&&y>=195&&y<=380)chooseSkill(i)}return}if(game.mode==="battle"&&x>=467&&x<=682&&y<=76){ultimate();return}if(game.mode==="result"){handleKey("Enter");return}if(game.mode==="lose"){game.mode="loadout";syncControls();return}if(game.mode==="ending"){toMap();return}});
document.querySelectorAll(".touchBtn").forEach(btn=>btn.addEventListener("pointerdown",e=>{e.preventDefault();handleKey(btn.dataset.code)}));let last=0;function update(dt){if(game.mode==="battle")updateBattle(dt)}function loop(ts){const dt=Math.min(.033,(ts-last||16)/1000);last=ts;update(dt);render();requestAnimationFrame(loop)}syncControls();requestAnimationFrame(loop);
window.__MIMIWORA_TEST__={unlockAll(){save.unlockedStage=5;for(const k of TYPES)save.weapons[k]=[0,1,2];store()},startStage(id){startStage(id)},setBattle(){game.mode="battle";syncControls()},forceLevel(k="mimi"){const h=game.heroes[k];h.level=Math.min(5,h.level+1);game.levelHero=h;game.skillCards=WEAPONS[k][h.weapon].skills;game.mode="upgrade";syncControls()},forceBoss(){game.stageT=game.stage.duration+1},win(){endBattle(true)}};