function diff(){return DIFF[save.difficulty]}
function makeHero(k){const b=HERO_BASE[k],wi=save.selected[k]||0,w=WEAPONS[k][wi],m=w.mods;return{type:k,name:b.name,x:HERO_X[k],weapon:wi,weaponName:w.name,hp:b.hp,maxHp:b.hp,atk:b.atk*(m.atk||1),rate:b.rate*(m.rate||1),range:b.range*(m.range||1),level:1,xp:0,nextXp:30,cd:0,anim:'idle',animT:0,splash:m.splash||0,slow:m.slow||0,crit:m.crit||.06,multishot:m.multishot||0,stun:m.stun||0,guard:m.guard||0,shock:m.shock||0,pierce:m.pierce||0,acid:m.acid||0,dot:m.dot||8,chain:m.chain||0,cannon:m.cannon||0,boomerang:m.boomerang||0,clone:m.clone||0,orbital:m.orbital||0,gravity:m.gravity||0,gravityRadius:120,spore:m.spore||0,sniper:m.sniper||0,execute:0,picked:[]}}
function resetBattle(id){game.stageId=id;game.stage=STAGES[id-1];game.heroes={};TYPES.forEach(k=>game.heroes[k]=makeHero(k));game.zombies=[];game.shots=[];game.fx=[];game.floaters=[];game.levelQueue=[];game.levelHero=null;game.wave=1;game.waveT=0;game.waveDur=26+id*3;game.spawnT=.5;game.gateMax=420;game.gateHP=420;game.kills=0;game.bossSpawned=false;game.team=0;game.combo=0;game.comboT=0;game.fever=0;game.shake=0;game.flash='';game.flashT=0;game.scrap=18;game.scrapMul=1;game.xpMul=1;game.relics=[];game.merchant=null;game.offers=[];game.merchantBought=false;game.crate=null;game.crateT=22;game.hazardT=18;game.skillCD={bomb:0,freeze:0,repair:0};game.skillLv={bomb:1,freeze:1,repair:1};setTheme(id)}
function story(lines,after){game.story=lines.map(a=>({speaker:a[0],text:a[1]}));game.storyI=0;game.storyAfter=after;game.mode='story'}function nextStory(){if(game.storyI<game.story.length-1){game.storyI++;tone(640,.03,'square',.025)}else{const f=game.storyAfter;game.storyAfter=null;if(f)f()}}function speakerType(s){return{MIMI:'mimi',GOBAN:'goban',NOMO:'nomo',KURO:'kuro'}[s]||null}
function startStage(id){resetBattle(id);story(STAGES[id-1].intro,()=>{game.mode='battle';game.flash='WAVE 1  '+game.stage.name;game.flashT=2})}
const STAGE_POOL={1:['walker','runner','tank','splitter','swarm','leaper'],2:['walker','acid','bomber','runner','spitter','nurse','parasite'],3:['shield','spitter','necro','splitter','brute','nurse','screamer'],4:['hunter','runner','shield','phantom','leaper','crusher','screamer'],5:['acid','bomber','shield','hunter','necro','phantom','crusher','nurse','screamer']};
const ELITES=[['狂暴','#ff765f',{spd:1.32,atk:1.22}],['裝甲','#9db5ca',{hp:1.55,armor:.16}],['再生','#8be6a0',{regen:2.2}],['吸血','#d88cff',{leech:.16}],['幽影','#93d5ff',{dodge:.18}]];
function spawn(type,count=1,forcedElite=false,x0=null,y0=null){const d=ENEMIES[type],df=diff(),stageMul=1+(game.stageId-1)*.20,waveMul=1+(game.wave-1)*.18;for(let i=0;i<count;i++){let elite=forcedElite||Math.random()<df.elite,aff=elite?pick(ELITES):null,hp=d.hp*df.hp*stageMul*waveMul,atk=d.atk*df.atk*(1+(game.stageId-1)*.06),spd=d.spd*df.spd;if(aff){if(aff[2].hp)hp*=aff[2].hp;if(aff[2].atk)atk*=aff[2].atk;if(aff[2].spd)spd*=aff[2].spd}game.zombies.push({type,x:x0??pick(LANES)+rnd(-18,18),y:y0??(900+rnd(0,80)),hp,max:hp,atk,spd,xp:d.xp,scrap:d.scrap,col:d.col,armor:(d.armor||0)+(aff?.[2].armor||0),dodge:(d.dodge||0)+(aff?.[2].dodge||0),regen:aff?.[2].regen||0,leech:aff?.[2].leech||0,elite,affix:aff?.[0]||'',affColor:aff?.[1]||'',hit:0,stun:0,slow:0,dot:0,dotT:0,cd:0,skillCd:rnd(3.5,6.5),anim:rnd(0,5),phase:0})}}
function spawnLogic(dt){game.spawnT-=dt;game.waveT+=dt;if(game.mode!=='battle')return;const df=diff();if(game.spawnT<=0&&!game.bossSpawned){let pool=STAGE_POOL[game.stageId].slice(0,Math.min(STAGE_POOL[game.stageId].length,3+game.wave*2)),type=pick(pool),n=(game.wave===3&&Math.random()<.16)?2:1;spawn(type,n);game.spawnT=Math.max(.17,(1.05-game.stageId*.04-game.wave*.08)*df.spawn*rnd(.72,1.18))}if(game.wave<=3&&game.waveT>game.waveDur){if(game.wave<3){game.mode='merchant';prepareMerchant();return}else if(!game.bossSpawned){game.bossSpawned=true;spawn('boss'+game.stageId,1,true,270,900);spawn(game.stageId<3?'tank':'brute',3,true);sfx('boss');game.flash='BOSS  '+game.stage.boss;game.flashT=2.4;game.shake=8}}}
function hazard(){game.hazardT=18+game.stageId*2;if(game.stageId===1){spawn('swarm',5);game.flash='屍潮警報！';game.flashT=1.3}if(game.stageId===2){for(const z of game.zombies)z.spd*=1.18;game.flash='黑雨：屍群加速！';game.flashT=1.3}if(game.stageId===3){for(const h of Object.values(game.heroes))h.cd+=1.2;game.flash='EMP：攻擊延遲！';game.flashT=1.3}if(game.stageId===4){for(const z of game.zombies)z.y-=55;game.shake=7;game.flash='列車暴走：屍群前衝！';game.flashT=1.3}if(game.stageId===5){game.team=Math.max(0,game.team-20);spawn(pick(['phantom','crusher','necro']),2,true);game.flash='末鐘脈衝！';game.flashT=1.3}}
function targetFor(h){let best=null,bd=1e9;for(const z of game.zombies){if(z.hp<=0)continue;let d=Math.hypot((z.x-h.x)*.8,z.y-235);if(d<h.range&&d<bd){best=z;bd=d}}return best}
function gainXP(h,a){if(h.level>=5)return;h.xp+=a*game.xpMul;while(h.level<5&&h.xp>=h.nextXp){h.xp-=h.nextXp;h.level++;h.nextXp=Math.round(h.nextXp*1.48+10);h.anim='celebrate';h.animT=1;sfx('level');game.levelQueue.push(h.type)}}
function flo(x,y,s,c='#fff'){game.floaters.push({x,y,s,c,t:.7})}
function damage(z,a,src,c='#fff'){if(z.hp<=0)return;if(z.dodge&&Math.random()<z.dodge){flo(z.x,z.y-55,'MISS','#aee8ff');return}let dealt=a*(1-clamp(z.armor||0,0,.65));if(src?.execute&&z.hp/z.max<.30)dealt*=1+src.execute;z.hp-=dealt;z.hit=.08;game.team=clamp(game.team+dealt*.06,0,100);flo(z.x,z.y-55,'-'+Math.round(dealt),c);if(z.hp<=0){game.kills++;game.combo++;game.comboT=2.1;game.scrap+=Math.ceil((z.scrap||2)*game.scrapMul);sfx('kill');if(game.combo>0&&game.combo%15===0){game.fever=6;game.flash='FEVER TIME！攻速提升';game.flashT=1.3;vib(40)}if(src){gainXP(src,z.xp);for(const k of TYPES)if(game.heroes[k]!==src)gainXP(game.heroes[k],Math.max(1,z.xp*.22))}if(ENEMIES[z.type]?.split)spawn('swarm',2,false,z.x+rnd(-20,20),z.y+10);game.fx.push({kind:'death',x:z.x,y:z.y-25,t:.3})}}
function attack(h,z){h.anim='attack';h.animT=.24;sfx(h.type);if(h.type==='mimi'){game.shots.push({kind:h.orbital?'orb':'star',x:h.x,y:205,target:z,spd:h.orbital?330:430,dmg:h.atk,src:h,splash:h.splash,slow:h.slow});if(Math.random()<h.multishot)game.shots.push({kind:'star',x:h.x+8,y:205,target:z,spd:455,dmg:h.atk*.7,src:h,splash:h.splash*.7,slow:h.slow})}else if(h.type==='goban'){if(h.gravity){for(const q of game.zombies){if(Math.hypot(q.x-z.x,q.y-z.y)<h.gravityRadius){q.x+=(z.x-q.x)*.12;q.y+=(z.y-q.y)*.05}}}if(h.cannon){game.shots.push({kind:'shell',x:h.x,y:205,target:z,spd:360,dmg:h.atk,src:h,splash:45+h.splash})}else{let rad=75+h.shock;game.fx.push({kind:'shock',x:h.x,y:225,t:.24,r:rad});for(const q of game.zombies)if(q.hp>0&&Math.hypot(q.x-h.x,q.y-320)<rad+80){damage(q,h.atk*(q===z?1:.55),h,'#ffd66d');if(Math.random()<h.stun)q.stun=Math.max(q.stun,.8)}}}else if(h.type==='nomo'){if(h.acid||h.spore){game.fx.push({kind:'acid',x:h.x,y:205,ex:z.x,ey:z.y-30,t:.15});for(const q of game.zombies.filter(q=>q.hp>0&&Math.hypot(q.x-z.x,q.y-z.y)<(h.splash||70)).slice(0,6)){damage(q,h.atk*.72,h,'#b8f181');q.dot=Math.max(q.dot,h.dot);q.dotT=3;q.slow=Math.max(q.slow,h.slow)}}else if(h.chain){let pool=game.zombies.filter(q=>q.hp>0).sort((a,b)=>Math.hypot(a.x-z.x,a.y-z.y)-Math.hypot(b.x-z.x,b.y-z.y));let cur={x:h.x,y:205};for(let i=0;i<Math.min(h.chain+1,pool.length);i++){let q=pool[i];damage(q,h.atk*(1-i*.13),h,'#9eefff');game.fx.push({kind:'arc',x:cur.x,y:cur.y,ex:q.x,ey:q.y-25,t:.12});cur=q}}else{game.fx.push({kind:'tongue',x:h.x,y:205,ex:z.x,ey:z.y-25,t:.15});for(const q of game.zombies.filter(q=>q.hp>0&&Math.abs(q.x-z.x)<38&&q.y>=z.y-30).slice(0,1+h.pierce))damage(q,h.atk,h,'#b9ed83')}}else{if(h.boomerang||h.sniper){game.shots.push({kind:h.sniper?'arrow':'ring',x:h.x,y:205,target:z,spd:h.sniper?620:450,dmg:h.atk,src:h,pierce:h.pierce||0,returning:false})}else{let crit=Math.random()<h.crit,d=h.atk*(crit?2.1:1);damage(z,d,h,crit?'#fff19b':'#e7e7ff');game.fx.push({kind:'slash',x:z.x,y:z.y-30,t:.14});if(Math.random()<h.clone)damage(z,h.atk*.75,h,'#c5c8ff')}}}
function updateShots(dt){for(const s of game.shots){if(s.kind==='ring'&&s.returning){let dx=s.src.x-s.x,dy=205-s.y,d=Math.hypot(dx,dy);if(d<12){s.dead=true;continue}s.x+=dx/d*s.spd*dt;s.y+=dy/d*s.spd*dt;continue}if(!s.target||s.target.hp<=0){if(s.kind==='ring'){s.returning=true;continue}s.dead=true;continue}let dx=s.target.x-s.x,dy=(s.target.y-30)-s.y,d=Math.hypot(dx,dy);if(d<14){damage(s.target,s.dmg,s.src,s.kind==='shell'?'#ffd58a':'#b7eeff');if(s.splash)for(const q of game.zombies)if(q!==s.target&&q.hp>0&&Math.hypot(q.x-s.target.x,q.y-s.target.y)<s.splash)damage(q,s.dmg*.42,s.src,'#9fdcff');if(s.slow)s.target.slow=Math.max(s.target.slow,s.slow);if(s.kind==='ring'){s.pierce--;if(s.pierce>=0){let n=game.zombies.find(q=>q.hp>0&&q!==s.target&&Math.hypot(q.x-s.target.x,q.y-s.target.y)<130);if(n){s.target=n;continue}}s.returning=true;continue}s.dead=true}else{s.x+=dx/d*s.spd*dt;s.y+=dy/d*s.spd*dt}}game.shots=game.shots.filter(s=>!s.dead)}
function updateZombies(dt){let guard=Math.max(...Object.values(game.heroes).map(h=>h.guard||0));for(const z of game.zombies){z.anim+=dt;z.hit=Math.max(0,z.hit-dt);z.stun=Math.max(0,z.stun-dt);z.cd-=dt;z.skillCd-=dt;if(z.regen)z.hp=Math.min(z.max,z.hp+z.regen*dt);if(z.dotT>0){z.dotT-=dt;if(Math.floor(z.dotT*4)!==Math.floor((z.dotT+dt)*4))damage(z,z.dot*.25,null,'#a8ef79')}if(z.hp<=0||z.stun>0)continue;if(ENEMIES[z.type]?.heal&&z.skillCd<=0){for(const q of game.zombies)if(q!==z&&Math.hypot(q.x-z.x,q.y-z.y)<120)q.hp=Math.min(q.max,q.hp+q.max*.08);z.skillCd=4.5;flo(z.x,z.y-60,'HEAL','#9dffb1')}if(ENEMIES[z.type]?.summon&&z.skillCd<=0){spawn('swarm',2,false,z.x,z.y+20);z.skillCd=5.5}if(ENEMIES[z.type]?.buff&&z.skillCd<=0){for(const q of game.zombies)if(Math.hypot(q.x-z.x,q.y-z.y)<120)q.spd*=1.08;z.skillCd=5}if(ENEMIES[z.type]?.leap&&z.skillCd<=0){z.y-=75;z.skillCd=5}const boss=z.type.startsWith('boss');if(boss&&z.hp/z.max<.5&&z.phase===0){z.phase=1;z.spd*=1.28;z.atk*=1.25;spawn(pick(STAGE_POOL[game.stageId]),4,true);game.flash='BOSS PHASE 2！';game.flashT=1.4;game.shake=7}if(boss&&z.skillCd<=0){spawn(pick(STAGE_POOL[game.stageId]),2+Math.floor(game.stageId/2),true);z.skillCd=5.5;game.shake=5}if(ENEMIES[z.type]?.ranged&&z.y<520&&z.y>330){if(z.cd<=0){game.gateHP-=z.atk*.55*(1-guard);flo(z.x,282,'遠射','#ffb5bf');z.cd=2.1;sfx('gate')}continue}if(z.y<=292){if(z.cd<=0){let dmg=z.atk*(1-guard);if(ENEMIES[z.type]?.bomb)dmg*=1.6;game.gateHP-=dmg;flo(z.x,280,'-'+Math.round(dmg),'#ffb5bf');z.cd=1;sfx('gate');game.shake=4;if(z.leech)z.hp=Math.min(z.max,z.hp+dmg*z.leech);if(ENEMIES[z.type]?.bomb)z.hp=0}}else z.y-=z.spd*(1-clamp(z.slow,0,.65))*dt}game.zombies=game.zombies.filter(z=>z.hp>0)}
const MERCHANTS=[
{name:'鐵匠・阿鋼',icon:'⚒',line:'唔夠痛？加到夠痛。',pool:['atk','speed','maxhp']},
{name:'修理婆婆',icon:'🧰',line:'城牆都識攰㗎。',pool:['repair','gate','repairSkill']},
{name:'黑市貓商',icon:'🐈',line:'貴，但通常值。通常。',pool:['crit','rareAtk','scrap']},
{name:'鍊金師・泡泡',icon:'⚗',line:'副作用？你唔問就冇。',pool:['xp','freeze','dot']},
{name:'遺物商人',icon:'◆',line:'舊世界留下嘅好東西。',pool:['range','ward','fever']},
{name:'流浪廚師',icon:'🍲',line:'食飽先有力打屍。',pool:['healAll','speedTemp','maxhp']},
{name:'武器技師',icon:'🔧',line:'我幫你把武器推過安全線。',pool:['atkHero','speedHero','rangeHero']},
{name:'占星商人',icon:'✦',line:'命運可以買，但唔平。',pool:['ult','crit','xp']}
];
function offerOf(key){const map={atk:{name:'全隊火力模組',desc:'全隊傷害 +14%',cost:46,do:()=>Object.values(game.heroes).forEach(h=>h.atk*=1.14)},speed:{name:'超頻齒輪',desc:'全隊攻速 +10%',cost:50,do:()=>Object.values(game.heroes).forEach(h=>h.rate*=.90)},maxhp:{name:'強化結構',desc:'城門最大 HP +70 並修 70',cost:48,do:()=>{game.gateMax+=70;game.gateHP=Math.min(game.gateMax,game.gateHP+70)}},repair:{name:'緊急焊接',desc:'城門修復 120 HP',cost:32,do:()=>game.gateHP=Math.min(game.gateMax,game.gateHP+120)},gate:{name:'防爆鋼板',desc:'城門最大 HP +100',cost:58,do:()=>{game.gateMax+=100;game.gateHP+=100}},repairSkill:{name:'維修無人機',desc:'維修技能冷卻 -25%',cost:55,do:()=>game.skillLv.repair++},crit:{name:'貓眼瞄具',desc:'全隊暴擊 +8%',cost:62,do:()=>Object.values(game.heroes).forEach(h=>h.crit+=.08)},rareAtk:{name:'禁制彈芯',desc:'全隊傷害 +22%',cost:82,do:()=>Object.values(game.heroes).forEach(h=>h.atk*=1.22)},scrap:{name:'磁力拾荒器',desc:'廢料收入 +35%',cost:52,do:()=>game.scrapMul*=1.35},xp:{name:'記憶晶片',desc:'經驗獲得 +30%',cost:48,do:()=>game.xpMul*=1.30},freeze:{name:'液氮增壓',desc:'冰封持續更長',cost:50,do:()=>game.skillLv.freeze++},dot:{name:'腐蝕催化劑',desc:'NOMO 持續傷害 +60%',cost:44,do:()=>game.heroes.nomo.dot*=1.6},range:{name:'觀測鏡片',desc:'全隊射程 +12%',cost:45,do:()=>Object.values(game.heroes).forEach(h=>h.range*=1.12)},ward:{name:'守護鐘石',desc:'GOBAN 額外城門減傷 +8%',cost:60,do:()=>game.heroes.goban.guard+=.08},fever:{name:'狂熱節拍器',desc:'FEVER 持續 +3 秒',cost:54,do:()=>game.relics.push('fever+')},healAll:{name:'熱湯套餐',desc:'城門 +80，技能全冷卻 -8 秒',cost:38,do:()=>{game.gateHP=Math.min(game.gateMax,game.gateHP+80);for(const k in game.skillCD)game.skillCD[k]=Math.max(0,game.skillCD[k]-8)}},speedTemp:{name:'辣椒濃湯',desc:'下波開始 FEVER 8 秒',cost:34,do:()=>game.fever=8},atkHero:{name:'主武器超頻',desc:'隨機英雄傷害 +35%',cost:58,do:()=>{let h=game.heroes[pick(TYPES)];h.atk*=1.35}},speedHero:{name:'伺服強化',desc:'隨機英雄攻速 +25%',cost:58,do:()=>{let h=game.heroes[pick(TYPES)];h.rate*=.75}},rangeHero:{name:'長距校準',desc:'隨機英雄射程 +35%',cost:46,do:()=>{let h=game.heroes[pick(TYPES)];h.range*=1.35}},ult:{name:'鐘芯充能器',desc:'立即充滿合技',cost:42,do:()=>game.team=100}};return Object.assign({key},map[key])}
function prepareMerchant(){game.merchant=pick(MERCHANTS);let keys=[...game.merchant.pool];while(keys.length<3)keys.push(pick(['atk','repair','crit','xp','range','scrap']));game.offers=keys.slice(0,3).map(offerOf);game.merchantBought=false;sfx('shop')}
function buyOffer(i){const o=game.offers[i];if(!o||game.merchantBought)return;if(game.scrap<o.cost){game.flash='廢料不足';game.flashT=1;return}game.scrap-=o.cost;o.do();game.merchantBought=true;sfx('coin');game.flash='購入：'+o.name;game.flashT=1.2}
function leaveMerchant(){game.wave++;game.waveT=0;game.waveDur=27+game.stageId*3+game.wave*2;game.mode='battle';game.flash='WAVE '+game.wave;game.flashT=1.5}
function openLevel(){let k=game.levelQueue.shift();if(!k)return;game.levelHero=game.heroes[k];game.skillCards=WEAPONS[k][game.levelHero.weapon].skills;game.mode='upgrade'}function chooseSkill(i){if(!game.levelHero)return;let s=game.skillCards[i];s[2](game.levelHero);game.levelHero.picked.push(s[0]);game.flash=game.levelHero.name+'：'+s[0];game.flashT=1.2;game.levelHero=null;game.skillCards=[];if(game.levelQueue.length)openLevel();else game.mode='battle'}
function tactical(key){if(game.mode!=='battle'||game.skillCD[key]>0)return;if(key==='bomb'){let dmg=70+game.skillLv.bomb*28;for(const z of game.zombies)damage(z,dmg,null,'#ffd07a');game.skillCD.bomb=Math.max(12,30-game.skillLv.bomb*3);game.fx.push({kind:'ult',t:.7});game.shake=7}if(key==='freeze'){for(const z of game.zombies){z.slow=Math.max(z.slow,.65);z.stun=Math.max(z.stun,1+game.skillLv.freeze*.5)}game.skillCD.freeze=Math.max(16,36-game.skillLv.freeze*3);game.flash='冰封脈衝！';game.flashT=1}if(key==='repair'){game.gateHP=Math.min(game.gateMax,game.gateHP+65+game.skillLv.repair*35);game.skillCD.repair=Math.max(20,48-game.skillLv.repair*5);game.flash='緊急維修';game.flashT=1}vib(30)}
function ultimate(){if(game.mode!=='battle'||game.team<100)return;game.team=0;sfx('ult');for(const z of game.zombies)damage(z,z.type.startsWith('boss')?115:78,null,'#c5f3ff');game.fx.push({kind:'ult',t:1.1});game.shake=9;vib(80)}