const DEFAULT_MODEL = process.env.OPENROUTER_MODEL || 'google/gemini-3.7-flash';
const ALLOWED = new Set([
  'https://boyman131418.github.io',
  'https://pianoforge-five-level-piano-6ngz3zrxq-boyman131418-9472.vercel.app',
  'https://pianoforge-ai-api.vercel.app'
]);
function cors(req,res){const origin=req.headers.origin||'';if(ALLOWED.has(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');}
function cleanJSON(text){if(typeof text!=='string')return text;const s=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');return JSON.parse(s)}
const schema={name:'piano_score_omr',strict:true,schema:{type:'object',additionalProperties:false,required:['title','composer','key','time_signature','tempo','overall_confidence','notes','melody','warnings'],properties:{title:{type:'string'},composer:{type:'string'},key:{type:'object',additionalProperties:false,required:['tonic','mode','fifths'],properties:{tonic:{type:'string'},mode:{type:'string',enum:['major','minor','unknown']},fifths:{anyOf:[{type:'integer',minimum:-7,maximum:7},{type:'null'}]}}},time_signature:{type:'object',additionalProperties:false,required:['beats','beat_type'],properties:{beats:{anyOf:[{type:'integer',minimum:1,maximum:12},{type:'null'}]},beat_type:{anyOf:[{type:'integer',enum:[1,2,4,8,16]},{type:'null'}]}}},tempo:{anyOf:[{type:'number',minimum:20,maximum:300},{type:'null'}]},overall_confidence:{type:'number',minimum:0,maximum:1},notes:{type:'array',maxItems:900,items:{type:'object',additionalProperties:false,required:['midi','start','duration','hand','measure','voice','confidence'],properties:{midi:{type:'integer',minimum:21,maximum:108},start:{type:'number',minimum:0},duration:{type:'number',exclusiveMinimum:0},hand:{type:'string',enum:['R','L']},measure:{type:'integer',minimum:1},voice:{type:'integer',minimum:1,maximum:4},confidence:{type:'number',minimum:0,maximum:1}}}},melody:{type:'array',maxItems:320,items:{type:'object',additionalProperties:false,required:['midi','start','duration','measure','confidence'],properties:{midi:{type:'integer',minimum:21,maximum:108},start:{type:'number',minimum:0},duration:{type:'number',exclusiveMinimum:0},measure:{type:'integer',minimum:1},confidence:{type:'number',minimum:0,maximum:1}}}},warnings:{type:'array',items:{type:'string'},maxItems:12}}}};
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!process.env.OPENROUTER_API_KEY)return res.status(503).json({error:'AI backend is not configured'});try{const {images,imageDataUrl,filename='score'}=req.body||{};let imgs=Array.isArray(images)?images.filter(x=>typeof x==='string'&&/^data:image\//.test(x)):(/^data:image\//.test(imageDataUrl||'')?[imageDataUrl]:[]);if(!imgs.length)return res.status(400).json({error:'score image is required'});if(imgs.length>5)imgs=imgs.slice(0,5);if(imgs.reduce((a,s)=>a+s.length,0)>15_000_000)return res.status(413).json({error:'Images are too large after compression'});
const system=`You are a professional optical music recognition specialist and conservatory-level piano engraver. Your job is data extraction, not creative completion. Read only notation visibly supported by the supplied score images. The first image is the full page; later images are overlapping high-resolution crops of the same page for detail checking. Reconcile them, do not duplicate notes. Use quarter-note units for time: quarter=1, eighth=.5, sixteenth=.25, dotted quarter=1.5, whole=4. Respect pickup measures if visible. Parse systems top-to-bottom and measures left-to-right. Treat grand staff correctly: treble usually hand R, bass usually hand L, but follow written cross-staff notation when clear. Preserve simultaneous chord notes at the same start. Preserve independent voices. If something is uncertain lower confidence rather than inventing. Identify time signature, key signature, tempo marking, note pitches, accidentals, rests through timing gaps, rhythmic values, ties when they affect sustained duration, and all clearly visible piano notes. Never collapse every note to quarter notes. Never infer notes merely from musical familiarity with the piece.`;
const prompt=`Analyze ${filename}. Return a complete structured piano transcription. Requirements: (1) time_signature must reflect the printed meter, e.g. 4/4; (2) durations must reflect printed rhythm, not a default value; (3) notes must include both hands and all clearly visible chord tones; (4) start values must preserve simultaneity and measure position; (5) voice numbers should distinguish independent stem directions where visible; (6) melody is only a convenience extraction and must not replace notes; (7) confidence below .75 for genuinely uncertain items. Do not omit notes simply because they require ledger lines. JSON only.`;
const content=[{type:'text',text:prompt},...imgs.map(url=>({type:'image_url',image_url:{url}}))];const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':'https://boyman131418.github.io/catman-ai-playground/pianoforge/','X-OpenRouter-Title':'PianoForge Pro'},body:JSON.stringify({model:DEFAULT_MODEL,temperature:0,max_tokens:18000,response_format:{type:'json_schema',json_schema:schema},messages:[{role:'system',content:system},{role:'user',content}]})});const raw=await r.json();if(!r.ok)return res.status(r.status).json({error:raw?.error?.message||'OpenRouter request failed'});let out=raw?.choices?.[0]?.message?.content;if(Array.isArray(out))out=out.map(x=>x?.text||'').join('');const score=cleanJSON(out);if(!Array.isArray(score?.notes)||!score.notes.length)return res.status(422).json({error:'AI could not extract a usable full score',score});return res.status(200).json({ok:true,model:DEFAULT_MODEL,score});}catch(e){return res.status(500).json({error:e?.message||'AI score analysis failed'})}}
